exclude: ^{{cookiecutter.project_slug}}/app/db/migrations/
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: '^{{cookiecutter\.project_slug}}/app/static/package.json$'
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
        exclude: '^{{cookiecutter\.project_slug}}/app/apps\.py$'
      - id: check-builtin-literals
        exclude: '^{{cookiecutter\.project_slug}}/app/apps\.py$'
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '^{{cookiecutter\.project_slug}}/app/apps\.py$'
      - id: ruff-format
        exclude: '^{{cookiecutter\.project_slug}}/app/apps\.py$'
